#!/bin/bash
set -ue

[ $# -eq 0 -o "$1" = "-h" -o "$1" = "--help" ] && echo "Usage: $0 [output_format] [input_file ...]" && exit 1

format="$1"
shift

case "$format" in
    h264|hevc) options="-an" ;;
    mp3|wav|flac|alac|aac|m4a|ac3) options="-vn" ;;
    mp4|webm|mkv|flv|ts|mov) options="-c copy" ;;
    *) echo "Unknown format, please specify options manually."; exit 1 ;;
esac

for i in "$@" ; do (
    set -x
    ffmpeg -i "$i" $options "${i%.*}.$format"
) done
